GET http://localhost:8080/api/persons

###
DELETE http://localhost:8080/api/persons/63b3453ad850ba503c50a3f7

###
GET http://localhost:8080/api/persons/63b34570ba82ec3dc6a10138

###
POST http://localhost:8080/api/persons
Content-Type: application/json

{
    "name": "John Arbuckle",
    "number": 43646
}